'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
<<<<<<< HEAD
'     Runtime Version:4.0.30319.42000
=======
'     Runtime Version:4.0.30319.34014
>>>>>>> origin/master
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

